volumes:
  mysql-data:
  rabbitmq-data:

services:
  app:
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh:cached

  pipe:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
     - "5672:5672"
     - "15672:15672"

networks:
  default:
    driver: bridge